
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
      - name: {{ .Values.image.app.name }}
        image: {{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}
        resources: {{- toYaml .Values.resources.app | nindent 10 }}
        env:
        - name: DB_HOST
          value: {{ .Chart.Name }}-db
        - name: DB_USER
          value: {{ .Values.mysql.user }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-db-secret
              key: password
        ports:
        - name: http
          containerPort: 80
