
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db-secret
type: Opaque
data:
  rootPassword: {{ .Values.mysql.rootPassword | b64enc }}
  password: {{ .Values.mysql.password | b64enc }}
