
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
spec:
  selector:
    app: {{ .Chart.Name }}-app
  ports:
    - protocol: {{ .Values.service.app.protocol }}
      port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
  type: {{ .Values.service.app.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
spec:
  selector:
    app: {{ .Chart.Name }}-db
  ports:
    - protocol: TCP
      port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.service.db.targetPort }}
  type: {{ .Values.service.db.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-node
spec:
  selector:
    app: {{ .Chart.Name }}-node
  ports:
    - protocol: TCP
      port: {{ .Values.service.node.port }}
      targetPort: {{ .Values.service.node.targetPort }}
  type: {{ .Values.service.node.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mailhog
spec:
  selector:
    app: {{ .Chart.Name }}-mailhog
  ports:
    - protocol: TCP
      port: {{ .Values.service.mailhog.one.port }}
      targetPort: {{ .Values.service.mailhog.one.targetPort }}
    - protocol: TCP
      port: {{ .Values.service.mailhog.two.port }}
      targetPort: {{ .Values.service.mailhog.two.targetPort }}
  type: {{ .Values.service.mailhog.one.type }}

